styling changes according to figma wireframe
speedrun-website/speedrun.website pull request #11
Opened 2021-07-21 15:26 UTC by NexusX45

## What
Changed the SiteNavbar to fit the Figma wireframe.

## Link to Issue
https://github.com/speedrun-website/speedrun.website/issues/6

## Acceptance

### Images
Default
![image](https://user-images.githubusercontent.com/48958189/126515376-0638aacd-8b32-43f3-9dc2-f2ddc4ce359c.png)

Mobile
![image](https://user-images.githubusercontent.com/48958189/126515493-4c573c65-ae54-4468-8c63-cedba1e7deee.png)

2021-07-21 18:20 UTC, maxcaplan requested changes
Looking good! I just added a couple notes for tweaks, there are a couple similar ones in there about using `space-x-` and `space-y-` on parent elements as apposed to applying margin to the child elements. 
You can read more about tailwinds space between class [here](https://tailwindcss.com/docs/space), it's pretty handy.

Once those get worked out we should be good to merge!

2021-07-21 18:20 UTC, maxcaplan commented on components/SiteNavbar.vue
> +      <div class="flex lg:hidden">
To space the buttons out I would suggest adding `flex-row space-x-2` to the parent flex div and removing `m-1` from the child buttons. Reduces the number of classes and makes the spacing more consistent.

2021-07-21 18:20 UTC, maxcaplan commented on components/SiteNavbar.vue
> +        >
could the padding be changed from `px-4 py-1` to `px-3 py-2` to make this button more consistent with the others?

2021-07-21 18:20 UTC, maxcaplan commented on components/SiteNavbar.vue
> +          lg:flex-row lg:w-auto lg:my-0
For this I would also suggest using `space-y-2` on the parent flex div as apposed to applying margin to the child buttons.

2021-07-21 18:20 UTC, maxcaplan commented on components/SiteNavbar.vue
> +          my-2
Could the `my-2` be removed? It creates a lot of white space in the hamburger menu in the mobile layout

2021-07-21 20:00 UTC, NexusX45 commented on components/SiteNavbar.vue
> +      <div class="flex lg:hidden">
Sure!

2021-07-21 21:20 UTC, NexusX45 commented
I've made the changes, can you take a look again?

2021-07-21 21:50 UTC, maxcaplan approved these changes

2021-07-21 21:51 UTC, maxcaplan commented
Things are looking good! I can go ahead and merge this unless there's something that others want added

2021-07-22 05:40 UTC, NexusX45 commented
Great!

2021-07-22 08:09 UTC, merged

2021-07-22 08:10 UTC, CapitaineToinon commented
Looks good, thanks for the PR 👍

2021-07-22 11:27 UTC, NexusX45 commented
Happy to help, thanks for accepting the PR